"""add user settings table

Revision ID: 00c17687deeb
Revises: a6e900c789b3
Create Date: 2026-05-22 04:12:32.999863

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '00c17687deeb'
down_revision: Union[str, Sequence[str], None] = 'a6e900c789b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_settings',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('currency', sa.String(length=10), server_default='CAD', nullable=False),
    sa.Column('date_format', sa.String(length=20), server_default='MM/DD/YYYY', nullable=False),
    sa.Column('fiscal_year_start', sa.Integer(), server_default='1', nullable=False),
    sa.Column('shift_late_income', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('income_cutoff_day', sa.Integer(), server_default='20', nullable=False),
    sa.Column('fi_target_override', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_settings')
    # ### end Alembic commands ###
