"""add_actual_amount_to_budget_values

Revision ID: 55f16bef95ea
Revises: a2b9c3562565
Create Date: 2026-05-06 00:03:16.865847

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '55f16bef95ea'
down_revision: Union[str, Sequence[str], None] = 'a2b9c3562565'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('budget_values', sa.Column('actual_amount', sa.Numeric(precision=12, scale=2), nullable=False, server_default='0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('budget_values', 'actual_amount')
    # ### end Alembic commands ###
