"""remove actual_amount from budget_values

Revision ID: a2b9c3562565
Revises: 0b60e9261e2b
Create Date: 2026-05-04 05:33:55.320809

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a2b9c3562565'
down_revision: Union[str, Sequence[str], None] = '0b60e9261e2b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('budget_values', 'actual_amount')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('budget_values', sa.Column('actual_amount', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
